### ISSUE TITLE
Missing Log levels from RFC 5424

### ISSUE THREAD

**Issue by Exadra37** [bunyan-logger/bunyan#1]
As per [RFC 5424](https://tools.ietf.org/html/rfc5424):

```
  Numerical         Severity
             Code

              0       Emergency: system is unusable
              1       Alert: action must be taken immediately
              2       Critical: critical conditions
              3       Error: error conditions
              4       Warning: warning conditions
              5       Notice: normal but significant condition
              6       Informational: informational messages
              7       Debug: debug-level messages

              Table 2. Syslog Message Severities
```

This library:
```
The log levels are debug, info, warn, and error, with debug being the lowest and error the highest.
```

So this library only goes until `error` and leaves 3 important ones out, `Critical`, `Alert` and `Emergency`.

While I may confess that I never used `Alert` I cannot say the same for `Critical` or even `Emergency`.

Do you consider to add the missing ones in order to make this exciting **Bunyan** logger ready for production use?

> PS: I really enjoyed your book and video course on Elixir and I love the your Components approach. Continue this excellent work :)

**Comment by pragdave** [comment]
I simply forward to the Elixir logger. If it supported these extra levels then I would too. I suggest raising the issue there.
