### ISSUE TITLE
404 response for link to Bunyan.Source.ErlangErrorLogger repository

### ISSUE THREAD

**Issue by Exadra37** [bunyan-logger/bunyan#2]
The [Components](https://github.com/bunyan-logger/bunyan#components) section have the link for [buyan_source_erlang_error_logger](https://github.com/bunyan-logger/buyan_source_erlang_error_logger) going to a `404` page:

![screenshot from 2019-02-05 21-17-54](https://user-images.githubusercontent.com/1745456/52305068-1f5f2480-298c-11e9-8aec-fd99fda07ac2.png)

The issue I see is that the repository is linking to have a typo in the name:

https://github.com/bunyan-logger/bunyan_sourcr_erlang_error_logger

The typo is in `_soucr_` while the the link in the Components section doesn't have the typo:

https://github.com/bunyan-logger/buyan_source_erlang_error_logger

In my opinion would be better to fix the repository with the typo, what do you think @pragdave ?

**Comment by pragdave** [comment]
Fixed #2 #3 #4 #5
