### ISSUE TITLE
404 response for link to Bunyan.Source.Api repository

### ISSUE THREAD

**Issue by Exadra37** [bunyan-logger/bunyan#3]
The [Components](https://github.com/bunyan-logger/bunyan#components) section have the link for [Bunyan Source API](https://github.com/bunyan-logger/bunyan_source_api) repository landing in a `404` page:

![screenshot from 2019-02-05 21-15-59](https://user-images.githubusercontent.com/1745456/52305605-6863a880-298d-11e9-9bcd-51e9f4d31346.png)

When visiting the list for all [Bunyan Logger](https://github.com/bunyan-logger) repositories I can't see one with that name...

Is this a future planned repository?

**Comment by pragdave** [comment]
Duplicate

**Comment by Exadra37** [comment]
Sorry but do you mind to say why is a duplicate and point to the original one... I think we deserve to know it after going to the effort of raising an issue ;)

Just an alert... this link is not the same as in the first issue I opened ;)
