### ISSUE TITLE
404 response for link to Bunyan.Source.Remote.Reader repository

### ISSUE THREAD

**Issue by Exadra37** [bunyan-logger/bunyan#4]
This link https://github.com/bunyan-logger/bunyan_source_remote_reader returns:

![screenshot from 2019-02-05 21-36-35](https://user-images.githubusercontent.com/1745456/52305945-5cc4b180-298e-11e9-944c-1d5ac60b8af7.png)

The issue is that the repository is linking to have a typo in the name:

https://github.com/bunyan-logger/bunyan_sourve_remote_reader

The typo is in `_sourve_` that should be `_source_`.

In my opinion the typo should be fixed in the repository we are linking to.

**Comment by pragdave** [comment]
Duplicate

**Comment by Exadra37** [comment]
Sorry but do you mind to say why is a duplicate and point to the original one... I think we deserve to know it after going to the effort of raising an issue ;)

Just an alert... this link is not the same as in the first issue I opened ;)
