### ISSUE TITLE
404 response for link to Bunyan.Writer.Remote respository

### ISSUE THREAD

**Issue by Exadra37** [bunyan-logger/bunyan#5]
The link to https://github.com/bunyan-logger/bunyan_writer_remote returns:

![screenshot from 2019-02-05 21-43-47](https://user-images.githubusercontent.com/1745456/52306224-29ceed80-298f-11e9-940c-12b0a41c6510.png)

The issue here is that the repository we are linking to have dashes `-` in the name while the link we use have underscores `_`.

Repository we are linking to:

https://github.com/bunyan-logger/bunyan-writer-remote

Link we use:

https://github.com/bunyan-logger/bunyan_writer_remote

**Comment by pragdave** [comment]
Duplicate

**Comment by Exadra37** [comment]
Sorry but do you mind to say why is a duplicate and point to the original one... I think we deserve to know it after going to the effort of raising an issue ;)

Just an alert... this link is not the same as in the first issue I opened ;)

**Comment by pragdave** [comment]
404 response for link to Bunyan.Writer.Remote respository
#5 by Exadra37 was closed 11 hours ago 
 2
404 response for link to Bunyan.Source.Remote.Reader repository
#4 by Exadra37 was closed 11 hours ago 
 2
404 response for link to Bunyan.Source.Api repository
#3 by Exadra37 was closed 11 hours ago 
 2
404 response for link to Bunyan.Source.ErlangErrorLogger repository
#2 opened 16 hours ago by Exadra37 

OK, they're not duplicates, but it is not typical to raise a separate issue for each typo you find. One would be sufficient.
